version: '2'
services:
  server:
    image: david3080/grpc-sample
    command: server
  webclient:
    image: david3080/grpc-sample
    command: webclient server:50051
    ports: 
      - '8080:8080'
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
